server:
  port: 8080

logging:
  level:
#    root: INFO
    root: DEBUG

spring:
  application:
    name: bal-server
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  jooq:
    sql-dialect: POSTGRES
